runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_APP: "app.py"
  FLASK_CONFIG: "production"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
